language: objective-c
cache: cocoapods
rvm: 2.7.0
osx_image: xcode11
before_install:
  - brew update

  # Only if app has Carthage dependencies
  - cd Code && carthage update --platform ios --new-resolver

script:
  - carthage build --no-skip-current
  - |
    xcodebuild test \
    -workspace Lexis.xcworkspace \
    -scheme Lexis \
    -sdk iphonesimulator \
    -destination 'platform=iOS Simulator,name=iPhone 8,OS=latest'
